### ISSUE TITLE
Intel AC-9560 Bluetooth

### ISSUE THREAD

**Issue by Joseph-Hui** [6923403/Dell-Inspiron-7590-Ventura#1]
我的7590的Wifi 是 Intel AC-9560. Wifi 沒問題，但藍芽用不了。會是什麼問題呢？

**Comment by vcvvvc** [comment]
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/tag/v2.3.0 ，蓝牙用的这个，这个问题你得自己调整一下，我这边正常用的，可以尝试重装kext跟调整下config.plist试试。 

另外那个hdmi，我平常也用不到就没有测试，得你自己试一下了

**Comment by Joseph-Hui** [comment]
iltwm 是kext 順序問題。我試了最新的，順序是 IntelBTPatch > IntelBlueFirmware > BlueToolFixup > Airportiltwm。還有是拿走了AirportBrcmFixup.
