### ISSUE TITLE
HDMI外置屏幕

### ISSUE THREAD

**Issue by Joseph-Hui** [6923403/Dell-Inspiron-7590-Ventura#2]
HDMI外置屏幕可以嗎？

**Comment by Joseph-Hui** [comment]
[外接显示器无反应解决方法,亲测可用 #123](https://github.com/Pinming/Dell-Inspiron-7590-Hackintosh-Opencore/issues/123)

**Comment by vcvvvc** [comment]
非常感谢，👍
